#include "stm32f4xx_hal.h"

STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_0 == (1UL << 0U), gpio_pin0_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_1 == (1UL << 1U), gpio_pin1_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_2 == (1UL << 2U), gpio_pin2_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_3 == (1UL << 3U), gpio_pin3_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_4 == (1UL << 4U), gpio_pin4_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_5 == (1UL << 5U), gpio_pin5_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_6 == (1UL << 6U), gpio_pin6_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_7 == (1UL << 7U), gpio_pin7_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_8 == (1UL << 8U), gpio_pin8_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_9 == (1UL << 9U), gpio_pin9_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_10 == (1UL << 10U), gpio_pin10_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_11 == (1UL << 11U), gpio_pin11_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_12 == (1UL << 12U), gpio_pin12_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_13 == (1UL << 13U), gpio_pin13_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_14 == (1UL << 14U), gpio_pin14_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_15 == (1UL << 15U), gpio_pin15_bit);
STM32_COMPAT_STATIC_ASSERT(GPIO_PIN_All == 0xFFFFU, gpio_pin_all_bits);
