#ifndef STM32F4XX_HAL_RCC_H
#define STM32F4XX_HAL_RCC_H

#include "stm32f4xx_hal_def.h"

typedef struct
{
    uint32_t PLLState;
    uint32_t PLLSource;
    uint32_t PLLM;
    uint32_t PLLN;
    uint32_t PLLP;
    uint32_t PLLQ;
} RCC_PLLInitTypeDef;

typedef struct
{
    uint32_t OscillatorType;
    uint32_t HSEState;
    uint32_t LSEState;
    uint32_t HSIState;
    uint32_t HSICalibrationValue;
    uint32_t LSIState;
    RCC_PLLInitTypeDef PLL;
} RCC_OscInitTypeDef;

typedef struct
{
    uint32_t ClockType;
    uint32_t SYSCLKSource;
    uint32_t AHBCLKDivider;
    uint32_t APB1CLKDivider;
    uint32_t APB2CLKDivider;
} RCC_ClkInitTypeDef;

#define RCC_OSCILLATORTYPE_NONE 0x00000000U
#define RCC_OSCILLATORTYPE_HSE  0x00000001U
#define RCC_OSCILLATORTYPE_HSI  0x00000002U
#define RCC_OSCILLATORTYPE_LSE  0x00000004U
#define RCC_OSCILLATORTYPE_LSI  0x00000008U

#define RCC_HSE_OFF    0x00000000U
#define RCC_HSE_ON     0x00000001U
#define RCC_HSE_BYPASS 0x00000005U
#define RCC_HSI_OFF    0x00000000U
#define RCC_HSI_ON     0x00000001U
#define RCC_HSICALIBRATION_DEFAULT 0x10U

#define RCC_PLL_NONE 0x00000000U
#define RCC_PLL_OFF  0x00000001U
#define RCC_PLL_ON   0x00000002U
#define RCC_PLLSOURCE_HSI 0x00000000U
#define RCC_PLLSOURCE_HSE 0x00000001U
#define RCC_PLLP_DIV2 2U
#define RCC_PLLP_DIV4 4U
#define RCC_PLLP_DIV6 6U
#define RCC_PLLP_DIV8 8U

#define RCC_CLOCKTYPE_SYSCLK 0x00000001U
#define RCC_CLOCKTYPE_HCLK   0x00000002U
#define RCC_CLOCKTYPE_PCLK1  0x00000004U
#define RCC_CLOCKTYPE_PCLK2  0x00000008U

#define RCC_SYSCLKSOURCE_HSI    0x00000000U
#define RCC_SYSCLKSOURCE_HSE    0x00000001U
#define RCC_SYSCLKSOURCE_PLLCLK 0x00000002U
#define RCC_SYSCLKSOURCE_STATUS_HSI    0x00000000U
#define RCC_SYSCLKSOURCE_STATUS_HSE    0x00000004U
#define RCC_SYSCLKSOURCE_STATUS_PLLCLK 0x00000008U

#define RCC_SYSCLK_DIV1   0x00000000U
#define RCC_SYSCLK_DIV2   0x00000080U
#define RCC_SYSCLK_DIV4   0x00000090U
#define RCC_SYSCLK_DIV8   0x000000A0U
#define RCC_SYSCLK_DIV16  0x000000B0U
#define RCC_SYSCLK_DIV64  0x000000C0U
#define RCC_SYSCLK_DIV128 0x000000D0U
#define RCC_SYSCLK_DIV256 0x000000E0U
#define RCC_SYSCLK_DIV512 0x000000F0U

#define RCC_HCLK_DIV1  0x00000000U
#define RCC_HCLK_DIV2  0x00001000U
#define RCC_HCLK_DIV4  0x00001400U
#define RCC_HCLK_DIV8  0x00001800U
#define RCC_HCLK_DIV16 0x00001C00U

#define IS_RCC_OSCILLATORTYPE(VALUE) (((VALUE) & ~0x0FU) == 0U)
#define IS_RCC_HSE(VALUE) (((VALUE) == RCC_HSE_OFF) || \
                           ((VALUE) == RCC_HSE_ON) || \
                           ((VALUE) == RCC_HSE_BYPASS))
#define IS_RCC_HSI(VALUE) (((VALUE) == RCC_HSI_OFF) || ((VALUE) == RCC_HSI_ON))
#define IS_RCC_PLL(VALUE) (((VALUE) == RCC_PLL_NONE) || \
                           ((VALUE) == RCC_PLL_OFF) || \
                           ((VALUE) == RCC_PLL_ON))

/* 常用外设时钟名按 STM32 编号映射到 GD32 的零起始编号。 */
#define GD32_HAL_RCC_ENABLE(periph) do { rcu_periph_clock_enable((periph)); } while (0U)
#define GD32_HAL_RCC_DISABLE(periph) do { rcu_periph_clock_disable((periph)); } while (0U)

#define __HAL_RCC_GPIOA_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_GPIOA)
#define __HAL_RCC_GPIOB_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_GPIOB)
#define __HAL_RCC_GPIOC_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_GPIOC)
#define __HAL_RCC_GPIOD_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_GPIOD)
#define __HAL_RCC_GPIOA_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_GPIOA)
#define __HAL_RCC_GPIOB_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_GPIOB)
#define __HAL_RCC_GPIOC_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_GPIOC)
#define __HAL_RCC_GPIOD_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_GPIOD)

#define __HAL_RCC_SYSCFG_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_AF)
#define __HAL_RCC_SYSCFG_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_AF)
#define __HAL_RCC_PWR_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_PMU)
#define __HAL_RCC_PWR_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_PMU)
#define __HAL_RCC_CRC_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_CRC)
#define __HAL_RCC_CRC_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_CRC)

#define __HAL_RCC_DMA1_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_DMA0)
#define __HAL_RCC_DMA2_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_DMA1)
#define __HAL_RCC_DMA1_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_DMA0)
#define __HAL_RCC_DMA2_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_DMA1)

#define __HAL_RCC_USART1_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_USART0)
#define __HAL_RCC_USART2_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_USART1)
#define __HAL_RCC_USART3_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_USART2)
#define __HAL_RCC_UART4_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_UART3)
#define __HAL_RCC_UART5_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_UART4)
#define __HAL_RCC_USART1_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_USART0)
#define __HAL_RCC_USART2_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_USART1)
#define __HAL_RCC_USART3_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_USART2)
#define __HAL_RCC_UART4_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_UART3)
#define __HAL_RCC_UART5_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_UART4)

#define __HAL_RCC_TIM1_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER0)
#define __HAL_RCC_TIM2_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER1)
#define __HAL_RCC_TIM3_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER2)
#define __HAL_RCC_TIM4_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER3)
#define __HAL_RCC_TIM5_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER4)
#define __HAL_RCC_TIM6_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER5)
#define __HAL_RCC_TIM7_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER6)
#define __HAL_RCC_TIM8_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER7)
#define __HAL_RCC_TIM9_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER8)
#define __HAL_RCC_TIM10_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER9)
#define __HAL_RCC_TIM11_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER10)
#define __HAL_RCC_TIM12_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER11)
#define __HAL_RCC_TIM13_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER12)
#define __HAL_RCC_TIM14_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_TIMER13)
#define __HAL_RCC_TIM1_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER0)
#define __HAL_RCC_TIM2_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER1)
#define __HAL_RCC_TIM3_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER2)
#define __HAL_RCC_TIM4_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER3)
#define __HAL_RCC_TIM5_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER4)
#define __HAL_RCC_TIM6_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER5)
#define __HAL_RCC_TIM7_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER6)
#define __HAL_RCC_TIM8_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER7)
#define __HAL_RCC_TIM9_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER8)
#define __HAL_RCC_TIM10_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER9)
#define __HAL_RCC_TIM11_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER10)
#define __HAL_RCC_TIM12_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER11)
#define __HAL_RCC_TIM13_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER12)
#define __HAL_RCC_TIM14_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_TIMER13)

#define __HAL_RCC_ADC1_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_ADC0)
#define __HAL_RCC_ADC2_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_ADC1)
#define __HAL_RCC_ADC3_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_ADC2)
#define __HAL_RCC_ADC1_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_ADC0)
#define __HAL_RCC_ADC2_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_ADC1)
#define __HAL_RCC_ADC3_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_ADC2)
#define __HAL_RCC_I2C1_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_I2C0)
#define __HAL_RCC_I2C2_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_I2C1)
#define __HAL_RCC_I2C1_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_I2C0)
#define __HAL_RCC_I2C2_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_I2C1)
#define __HAL_RCC_SPI1_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_SPI0)
#define __HAL_RCC_SPI2_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_SPI1)
#define __HAL_RCC_SPI3_CLK_ENABLE() GD32_HAL_RCC_ENABLE(RCU_SPI2)
#define __HAL_RCC_SPI1_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_SPI0)
#define __HAL_RCC_SPI2_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_SPI1)
#define __HAL_RCC_SPI3_CLK_DISABLE() GD32_HAL_RCC_DISABLE(RCU_SPI2)

/* GD32F403RET6 没有 I2C2（STM32 命名下的 I2C3）；使用即产生明确编译错误。 */
#define __HAL_RCC_I2C3_CLK_ENABLE() ((void)sizeof(GD32_HAL_UNSUPPORTED_I2C3_ON_GD32F403RET6))

HAL_StatusTypeDef HAL_RCC_DeInit(void);
HAL_StatusTypeDef HAL_RCC_OscConfig(const RCC_OscInitTypeDef *RCC_OscInitStruct);
HAL_StatusTypeDef HAL_RCC_ClockConfig(const RCC_ClkInitTypeDef *RCC_ClkInitStruct,
                                      uint32_t FLatency);
uint32_t HAL_RCC_GetSysClockFreq(void);
uint32_t HAL_RCC_GetHCLKFreq(void);
uint32_t HAL_RCC_GetPCLK1Freq(void);
uint32_t HAL_RCC_GetPCLK2Freq(void);
void HAL_RCC_GetOscConfig(RCC_OscInitTypeDef *RCC_OscInitStruct);
void HAL_RCC_GetClockConfig(RCC_ClkInitTypeDef *RCC_ClkInitStruct,
                            uint32_t *pFLatency);
void HAL_RCC_EnableCSS(void);
void HAL_RCC_DisableCSS(void);
void HAL_RCC_NMI_IRQHandler(void);
void HAL_RCC_CSSCallback(void);

#endif /* STM32F4XX_HAL_RCC_H */
