#ifndef STM32F4XX_HAL_CONF_H
#define STM32F4XX_HAL_CONF_H

/* 仅启用已经提交实现并进入回归检查的兼容模块。 */
#define HAL_MODULE_ENABLED
#define HAL_GPIO_MODULE_ENABLED
#define HAL_CORTEX_MODULE_ENABLED
#define HAL_RCC_MODULE_ENABLED
#define HAL_UART_MODULE_ENABLED
#define HAL_DMA_MODULE_ENABLED
#define HAL_TIM_MODULE_ENABLED
#define HAL_ADC_MODULE_ENABLED
#define HAL_I2C_MODULE_ENABLED
#define HAL_SPI_MODULE_ENABLED
#define HAL_EXTI_MODULE_ENABLED
#define HAL_FLASH_MODULE_ENABLED

/* 默认保护 HXTAL 使用的 PD0/PD1；仅在停用 HXTAL 并完成 remap 后改为 1。 */
#ifndef GD32_HAL_ALLOW_PD01_GPIO
#define GD32_HAL_ALLOW_PD01_GPIO 0U
#endif

/* GD32F403 数据手册：VDDA/VREFP >= 2.6 V 时 CK_ADC 为 0.1..40 MHz。 */
#ifndef GD32_HAL_ADC_MAX_CLOCK_HZ
#define GD32_HAL_ADC_MAX_CLOCK_HZ 40000000UL
#endif

#ifndef GD32_HAL_ADC_MIN_CLOCK_HZ
#define GD32_HAL_ADC_MIN_CLOCK_HZ 100000UL
#endif

#ifndef GD32_HAL_RCC_SWITCH_TIMEOUT_CYCLES
#define GD32_HAL_RCC_SWITCH_TIMEOUT_CYCLES 1000000UL
#endif

#ifndef TICK_INT_PRIORITY
#define TICK_INT_PRIORITY 0x0FU
#endif

#ifndef USE_RTOS
#define USE_RTOS 0U
#endif

#ifndef USE_FULL_ASSERT
#define USE_FULL_ASSERT 0U
#endif

#ifndef USE_HAL_UART_REGISTER_CALLBACKS
#define USE_HAL_UART_REGISTER_CALLBACKS 0U
#endif

#ifndef USE_HAL_TIM_REGISTER_CALLBACKS
#define USE_HAL_TIM_REGISTER_CALLBACKS 0U
#endif

#ifndef USE_HAL_ADC_REGISTER_CALLBACKS
#define USE_HAL_ADC_REGISTER_CALLBACKS 0U
#endif

#ifndef USE_HAL_I2C_REGISTER_CALLBACKS
#define USE_HAL_I2C_REGISTER_CALLBACKS 0U
#endif

#ifndef USE_HAL_SPI_REGISTER_CALLBACKS
#define USE_HAL_SPI_REGISTER_CALLBACKS 0U
#endif

#endif /* STM32F4XX_HAL_CONF_H */
