#ifndef STM32F4XX_HAL_RCC_H
#define STM32F4XX_HAL_RCC_H

#include "stm32f4xx_hal_def.h"

typedef struct
{
    uint32_t PLLState;
    uint32_t PLLSource;
    uint32_t PLLM;
    uint32_t PLLN;
    uint32_t PLLP;
    uint32_t PLLQ;
} RCC_PLLInitTypeDef;

typedef struct
{
    uint32_t OscillatorType;
    uint32_t HSEState;
    uint32_t LSEState;
    uint32_t HSIState;
    uint32_t HSICalibrationValue;
    uint32_t LSIState;
    RCC_PLLInitTypeDef PLL;
} RCC_OscInitTypeDef;

typedef struct
{
    uint32_t ClockType;
    uint32_t SYSCLKSource;
    uint32_t AHBCLKDivider;
    uint32_t APB1CLKDivider;
    uint32_t APB2CLKDivider;
} RCC_ClkInitTypeDef;

#define RCC_OSCILLATORTYPE_NONE 0x00000000U
#define RCC_OSCILLATORTYPE_HSE  0x00000001U
#define RCC_OSCILLATORTYPE_HSI  0x00000002U
#define RCC_OSCILLATORTYPE_LSE  0x00000004U
#define RCC_OSCILLATORTYPE_LSI  0x00000008U

#define RCC_HSE_OFF    0x00000000U
#define RCC_HSE_ON     0x00000001U
#define RCC_HSE_BYPASS 0x00000005U
#define RCC_HSI_OFF    0x00000000U
#define RCC_HSI_ON     0x00000001U
#define RCC_HSICALIBRATION_DEFAULT 0x10U

#define RCC_PLL_NONE 0x00000000U
#define RCC_PLL_OFF  0x00000001U
#define RCC_PLL_ON   0x00000002U
#define RCC_PLLSOURCE_HSI 0x00000000U
#define RCC_PLLSOURCE_HSE 0x00000001U
#define RCC_PLLP_DIV2 2U
#define RCC_PLLP_DIV4 4U
#define RCC_PLLP_DIV6 6U
#define RCC_PLLP_DIV8 8U

#define RCC_CLOCKTYPE_SYSCLK 0x00000001U
#define RCC_CLOCKTYPE_HCLK   0x00000002U
#define RCC_CLOCKTYPE_PCLK1  0x00000004U
#define RCC_CLOCKTYPE_PCLK2  0x00000008U

#define RCC_SYSCLKSOURCE_HSI    0x00000000U
#define RCC_SYSCLKSOURCE_HSE    0x00000001U
#define RCC_SYSCLKSOURCE_PLLCLK 0x00000002U
#define RCC_SYSCLKSOURCE_STATUS_HSI    0x00000000U
#define RCC_SYSCLKSOURCE_STATUS_HSE    0x00000004U
#define RCC_SYSCLKSOURCE_STATUS_PLLCLK 0x00000008U

#define RCC_SYSCLK_DIV1   0x00000000U
#define RCC_SYSCLK_DIV2   0x00000080U
#define RCC_SYSCLK_DIV4   0x00000090U
#define RCC_SYSCLK_DIV8   0x000000A0U
#define RCC_SYSCLK_DIV16  0x000000B0U
#define RCC_SYSCLK_DIV64  0x000000C0U
#define RCC_SYSCLK_DIV128 0x000000D0U
#define RCC_SYSCLK_DIV256 0x000000E0U
#define RCC_SYSCLK_DIV512 0x000000F0U

#define RCC_HCLK_DIV1  0x00000000U
#define RCC_HCLK_DIV2  0x00001000U
#define RCC_HCLK_DIV4  0x00001400U
#define RCC_HCLK_DIV8  0x00001800U
#define RCC_HCLK_DIV16 0x00001C00U

/*
 * 只公开与 GD32F403 reset cause 有明确一一对应的 STM32 标志。
 * BORRST 在 GD32F403 RCU 中没有独立等价标志，因此不定义。
 */
#define RCC_FLAG_PINRST  GD32_HAL_RCC_RESET_FLAG_PIN
#define RCC_FLAG_PORRST  GD32_HAL_RCC_RESET_FLAG_POWER
#define RCC_FLAG_SFTRST  GD32_HAL_RCC_RESET_FLAG_SOFTWARE
#define RCC_FLAG_IWDGRST GD32_HAL_RCC_RESET_FLAG_INDEPENDENT_WATCHDOG
#define RCC_FLAG_WWDGRST GD32_HAL_RCC_RESET_FLAG_WINDOW_WATCHDOG
#define RCC_FLAG_LPWRRST GD32_HAL_RCC_RESET_FLAG_LOW_POWER

#define __HAL_RCC_GET_FLAG(__FLAG__) \
    (GD32_HAL_RCC_GetResetFlag((GD32_HAL_RCCResetFlag)(__FLAG__)) != 0U)
#define __HAL_RCC_CLEAR_RESET_FLAGS() \
    do { GD32_HAL_RCC_ClearResetFlags(); } while (0)

#define IS_RCC_OSCILLATORTYPE(VALUE) (((VALUE) & ~0x0FU) == 0U)
#define IS_RCC_HSE(VALUE) (((VALUE) == RCC_HSE_OFF) || \
                           ((VALUE) == RCC_HSE_ON) || \
                           ((VALUE) == RCC_HSE_BYPASS))
#define IS_RCC_HSI(VALUE) (((VALUE) == RCC_HSI_OFF) || ((VALUE) == RCC_HSI_ON))
#define IS_RCC_PLL(VALUE) (((VALUE) == RCC_PLL_NONE) || \
                           ((VALUE) == RCC_PLL_OFF) || \
                           ((VALUE) == RCC_PLL_ON))

/* 公共宏只传递 STM32 语义资源；实际 RCU 枚举和 SPL 调用留在 Port。 */
#define STM32_HAL_RCC_INSTANCE_CLOCK(INSTANCE, KIND, ENABLE) \
    ((void)GD32_HAL_RCC_SetInstanceClock((uintptr_t)(INSTANCE), (KIND), (ENABLE)))
#define STM32_HAL_RCC_COMMON_CLOCK(CLOCK, ENABLE) \
    ((void)GD32_HAL_RCC_SetCommonClock((CLOCK), (ENABLE)))

#define __HAL_RCC_GPIOA_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_GPIO_INSTANCE_A, GD32_HAL_RESOURCE_GPIO, 1)
#define __HAL_RCC_GPIOB_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_GPIO_INSTANCE_B, GD32_HAL_RESOURCE_GPIO, 1)
#define __HAL_RCC_GPIOC_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_GPIO_INSTANCE_C, GD32_HAL_RESOURCE_GPIO, 1)
#define __HAL_RCC_GPIOD_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_GPIO_INSTANCE_D, GD32_HAL_RESOURCE_GPIO, 1)
#define __HAL_RCC_GPIOA_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_GPIO_INSTANCE_A, GD32_HAL_RESOURCE_GPIO, 0)
#define __HAL_RCC_GPIOB_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_GPIO_INSTANCE_B, GD32_HAL_RESOURCE_GPIO, 0)
#define __HAL_RCC_GPIOC_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_GPIO_INSTANCE_C, GD32_HAL_RESOURCE_GPIO, 0)
#define __HAL_RCC_GPIOD_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_GPIO_INSTANCE_D, GD32_HAL_RESOURCE_GPIO, 0)

#define __HAL_RCC_SYSCFG_CLK_ENABLE() STM32_HAL_RCC_COMMON_CLOCK(GD32_HAL_RCC_COMMON_AF, 1)
#define __HAL_RCC_SYSCFG_CLK_DISABLE() STM32_HAL_RCC_COMMON_CLOCK(GD32_HAL_RCC_COMMON_AF, 0)
#define __HAL_RCC_PWR_CLK_ENABLE() STM32_HAL_RCC_COMMON_CLOCK(GD32_HAL_RCC_COMMON_PMU, 1)
#define __HAL_RCC_PWR_CLK_DISABLE() STM32_HAL_RCC_COMMON_CLOCK(GD32_HAL_RCC_COMMON_PMU, 0)
#define __HAL_RCC_CRC_CLK_ENABLE() STM32_HAL_RCC_COMMON_CLOCK(GD32_HAL_RCC_COMMON_CRC, 1)
#define __HAL_RCC_CRC_CLK_DISABLE() STM32_HAL_RCC_COMMON_CLOCK(GD32_HAL_RCC_COMMON_CRC, 0)

#define __HAL_RCC_DMA1_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_DMA0_CHANNEL0, GD32_HAL_RESOURCE_DMA, 1)
#define __HAL_RCC_DMA2_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_DMA1_CHANNEL0, GD32_HAL_RESOURCE_DMA, 1)
#define __HAL_RCC_DMA1_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_DMA0_CHANNEL0, GD32_HAL_RESOURCE_DMA, 0)
#define __HAL_RCC_DMA2_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_DMA1_CHANNEL0, GD32_HAL_RESOURCE_DMA, 0)

#define __HAL_RCC_USART1_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_UART_INSTANCE_1, GD32_HAL_RESOURCE_UART, 1)
#define __HAL_RCC_USART2_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_UART_INSTANCE_2, GD32_HAL_RESOURCE_UART, 1)
#define __HAL_RCC_USART6_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_UART_INSTANCE_6, GD32_HAL_RESOURCE_UART, 1)
#define __HAL_RCC_USART1_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_UART_INSTANCE_1, GD32_HAL_RESOURCE_UART, 0)
#define __HAL_RCC_USART2_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_UART_INSTANCE_2, GD32_HAL_RESOURCE_UART, 0)
#define __HAL_RCC_USART6_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_UART_INSTANCE_6, GD32_HAL_RESOURCE_UART, 0)

#define __HAL_RCC_TIM1_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_1, GD32_HAL_RESOURCE_TIMER, 1)
#define __HAL_RCC_TIM2_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_2, GD32_HAL_RESOURCE_TIMER, 1)
#define __HAL_RCC_TIM3_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_3, GD32_HAL_RESOURCE_TIMER, 1)
#define __HAL_RCC_TIM4_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_4, GD32_HAL_RESOURCE_TIMER, 1)
#define __HAL_RCC_TIM5_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_5, GD32_HAL_RESOURCE_TIMER, 1)
#define __HAL_RCC_TIM9_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_9, GD32_HAL_RESOURCE_TIMER, 1)
#define __HAL_RCC_TIM10_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_10, GD32_HAL_RESOURCE_TIMER, 1)
#define __HAL_RCC_TIM11_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_11, GD32_HAL_RESOURCE_TIMER, 1)
#define __HAL_RCC_TIM1_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_1, GD32_HAL_RESOURCE_TIMER, 0)
#define __HAL_RCC_TIM2_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_2, GD32_HAL_RESOURCE_TIMER, 0)
#define __HAL_RCC_TIM3_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_3, GD32_HAL_RESOURCE_TIMER, 0)
#define __HAL_RCC_TIM4_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_4, GD32_HAL_RESOURCE_TIMER, 0)
#define __HAL_RCC_TIM5_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_5, GD32_HAL_RESOURCE_TIMER, 0)
#define __HAL_RCC_TIM9_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_9, GD32_HAL_RESOURCE_TIMER, 0)
#define __HAL_RCC_TIM10_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_10, GD32_HAL_RESOURCE_TIMER, 0)
#define __HAL_RCC_TIM11_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_TIM_INSTANCE_11, GD32_HAL_RESOURCE_TIMER, 0)

#define __HAL_RCC_ADC1_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_ADC_INSTANCE_1, GD32_HAL_RESOURCE_ADC, 1)
#define __HAL_RCC_ADC1_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_ADC_INSTANCE_1, GD32_HAL_RESOURCE_ADC, 0)
#define __HAL_RCC_I2C1_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_I2C_INSTANCE_1, GD32_HAL_RESOURCE_I2C, 1)
#define __HAL_RCC_I2C2_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_I2C_INSTANCE_2, GD32_HAL_RESOURCE_I2C, 1)
#define __HAL_RCC_I2C1_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_I2C_INSTANCE_1, GD32_HAL_RESOURCE_I2C, 0)
#define __HAL_RCC_I2C2_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_I2C_INSTANCE_2, GD32_HAL_RESOURCE_I2C, 0)
#define __HAL_RCC_SPI1_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_SPI_INSTANCE_1, GD32_HAL_RESOURCE_SPI, 1)
#define __HAL_RCC_SPI2_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_SPI_INSTANCE_2, GD32_HAL_RESOURCE_SPI, 1)
#define __HAL_RCC_SPI3_CLK_ENABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_SPI_INSTANCE_3, GD32_HAL_RESOURCE_SPI, 1)
#define __HAL_RCC_SPI1_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_SPI_INSTANCE_1, GD32_HAL_RESOURCE_SPI, 0)
#define __HAL_RCC_SPI2_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_SPI_INSTANCE_2, GD32_HAL_RESOURCE_SPI, 0)
#define __HAL_RCC_SPI3_CLK_DISABLE() STM32_HAL_RCC_INSTANCE_CLOCK(STM32_SPI_INSTANCE_3, GD32_HAL_RESOURCE_SPI, 0)

/* GD32F403RET6 没有 I2C2（STM32 命名下的 I2C3）；使用即产生明确编译错误。 */
#define __HAL_RCC_I2C3_CLK_ENABLE() ((void)sizeof(GD32_HAL_UNSUPPORTED_I2C3_ON_GD32F403RET6))
#define __HAL_RCC_I2C3_CLK_DISABLE() ((void)sizeof(GD32_HAL_UNSUPPORTED_I2C3_ON_GD32F403RET6))

HAL_StatusTypeDef HAL_RCC_DeInit(void);
HAL_StatusTypeDef HAL_RCC_OscConfig(const RCC_OscInitTypeDef *RCC_OscInitStruct);
HAL_StatusTypeDef HAL_RCC_ClockConfig(const RCC_ClkInitTypeDef *RCC_ClkInitStruct,
                                      uint32_t FLatency);
uint32_t HAL_RCC_GetSysClockFreq(void);
uint32_t HAL_RCC_GetHCLKFreq(void);
uint32_t HAL_RCC_GetPCLK1Freq(void);
uint32_t HAL_RCC_GetPCLK2Freq(void);
void HAL_RCC_GetOscConfig(RCC_OscInitTypeDef *RCC_OscInitStruct);
void HAL_RCC_GetClockConfig(RCC_ClkInitTypeDef *RCC_ClkInitStruct,
                            uint32_t *pFLatency);
void HAL_RCC_EnableCSS(void);
void HAL_RCC_DisableCSS(void);
void HAL_RCC_NMI_IRQHandler(void);
void HAL_RCC_CSSCallback(void);

#endif /* STM32F4XX_HAL_RCC_H */
